# Generated by Django 5.1.4 on 2024-12-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_language_slug_alter_topic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='keywords',
            field=models.TextField(default=''),
        ),
    ]
